Fix `-h` option conflict in fridge_mqtt.py
Fix the following error in fridge_mqtt.py:

argparse.ArgumentError: argument -h/--mqtt-host: conflicting option string: -h